# Generated by Django 5.2.10 on 2026-01-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_type',
            field=models.CharField(choices=[('sqft', 'Square Feet (Sq.Ft)'), ('sqm', 'Square Meter (Sq.M)'), ('rft', 'Running Feet (R.Ft)'), ('rm', 'Running Meter (R.M)'), ('cft', 'Cubic Feet (Cu.Ft)'), ('cum', 'Cubic Meter (Cu.M)'), ('nos', 'Numbers (Nos)'), ('kg', 'Kilogram (Kg)'), ('ton', 'Metric Ton'), ('bag', 'Bags'), ('ltr', 'Liters'), ('ls', 'Lump Sum (L.S)'), ('day', 'Per Day'), ('hr', 'Per Hour'), ('trip', 'Per Trip'), ('load', 'Per Load'), ('lot', 'Per Lot'), ('each', 'Each')], default='nos', max_length=20, verbose_name='Unit'),
        ),
    ]
