# Generated by Django 5.2.10 on 2026-02-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_quotation',
            field=models.BooleanField(default=False, help_text='Check this to create a Quotation instead of Invoice', verbose_name='Mark as Quotation'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_type',
            field=models.CharField(choices=[('sqft', 'Square Feet (Sq.Ft)'), ('sqm', 'Square Meter (Sq.M)'), ('nos', 'Numbers (Nos)'), ('ls', 'Lump Sum (L.S)')], default='nos', max_length=20, verbose_name='Unit'),
        ),
    ]
